// generated 2003/10/10 13:21:01 CEST by thoma@Tiger.(none)
// using glademm V2.0.0c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/thoma/rollenspiel/rps/rpgs.glade
// for gtk 2.2.4 and gtkmm 2.2.7
//
// Please modify the corresponding derived classes in ./src/main_window_RPS.hh and./src/main_window_RPS.cc

#ifndef _MAIN_WINDOW_RPS_GLADE_HH
#  define _MAIN_WINDOW_RPS_GLADE_HH


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/window.h>
#include <gtkmm/tooltips.h>
#include <gtkmm/togglebutton.h>
#include <gtkmm/treeview.h>
#include <gtkmm/viewport.h>
#include <gtkmm/scrolledwindow.h>

class main_window_RPS_glade : public Gtk::Window
{  
        
        GlademmData *gmm_data;
        Gtk::Tooltips _tooltips;
protected:
        class Gtk::ToggleButton *togglebutton_play_dir;
        class Gtk::ToggleButton *togglebutton_repeat;
        class Gtk::ToggleButton *togglebutton_kill_on_new;
        class Gtk::TreeView *treeview_main;
        class Gtk::Viewport *viewport_playlist;
        class Gtk::ScrolledWindow *scrolledwindow_playlist;
        
        main_window_RPS_glade();
        
        ~main_window_RPS_glade();
private:
        virtual void on_button_quit_clicked() = 0;
        virtual void on_togglebutton_play_dir_toggled() = 0;
        virtual void on_button_stop_CD_clicked() = 0;
        virtual void on_togglebutton_repeat_toggled() = 0;
        virtual void on_togglebutton_kill_on_new_toggled() = 0;
        virtual void on_button_stop_now_clicked() = 0;
        virtual void on_treeview_main_row_activated(const Gtk::TreeModel::Path& path, Gtk::TreeViewColumn* column) = 0;
        virtual void on_treeview_main_cursor_changed() = 0;
        virtual bool on_treeview_main_move_cursor(Gtk::MovementStep step, int count) = 0;
        virtual void on_treeview_main_select_cursor_row(bool start_editing) = 0;
        virtual void on_treeview_main_toggle_cursor_row() = 0;
        virtual void on_treeview_main_start_interactive_search() = 0;
        virtual bool on_treeview_main_button_release_event(GdkEventButton *ev) = 0;
        virtual void on_treeview_main_row_expanded(const Gtk::TreeModel::iterator& iter, const Gtk::TreeModel::Path& path) = 0;
        virtual bool on_main_window_RPS_delete_event(GdkEventAny *ev) = 0;
};
#endif
